name: Publish Docker Image ðŸ³

on:
  workflow_run:
    workflows: ["Finalize Release â›µ"]
    types: [completed]

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Docker Image ðŸ³
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code âœï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all tags and history

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "Found tag: ${TAG}"
          # Check out the tagged commit
          git checkout ${TAG}

      - name: Login to Docker Hub ðŸ”’
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU ðŸ”¨
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx ðŸ”§
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) ðŸ’‰
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alamellama/mkdocs-publisher
          tags: |
            type=raw,value=latest
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Build distribution ðŸ“¦
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
